### ISSUE TITLE
Crashes in 1.20 when opening the inventory screen

### ISSUE THREAD

**Issue by VideoGameSmash12** [VideoGameSmash12/HotbarsPlus#29]
```none
[15:52:27] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_40199
	at net.minecraft.class_481.handler$zon000$hotbarsplus-1_19_3$injInit(class_481.java:1602) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25426(class_481.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25426(class_490.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2009) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by VideoGameSmash12** [comment]
Fixed in v2.0-pre12
